name: fastapi-book-project

services:
  api:
    image: api:book
    build:
      context: .
      dockerfile: Dockerfile
    
    networks:
      - app-network
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7001/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 10
  web:
    image: nginx:alpine3.21-slim
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge